apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleetpro
resources:
  - job.yaml

images:
  - name: fleetpro-backend
    newName: rg.fr-par.scw.cloud/your-namespace/fleetpro-backend
    newTag: latest
